# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman_core', '0002_rename_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='channel_boswell',
            field=models.BooleanField(default=False, verbose_name='OpenClaw notifications'),
        ),
    ]
