# Generated by Django 6.0.3 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman_core', '0003_notificationpreference_channel_boswell'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='yeoman_core_user_id_8843da_idx',
            old_name='core_calend_user_id_516290_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='yeoman_core_externa_9b85b1_idx',
            old_name='core_calend_externa_294264_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='yeoman_core_content_fd5ed9_idx',
            old_name='core_calend_content_0f5a35_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='yeoman_core_status_87c6f5_idx',
            old_name='core_calend_status_0f32b6_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarsynclog',
            new_name='yeoman_core_user_id_4c65f8_idx',
            old_name='core_calend_user_id_920c58_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='yeoman_core_recipie_e86ea8_idx',
            old_name='core_notifi_recipie_f4ed05_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive')], max_length=25),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='yeoman_core_auditlog',
        ),
        migrations.AlterModelTable(
            name='calendarevent',
            table='yeoman_core_calendarevent',
        ),
        migrations.AlterModelTable(
            name='calendarsynclog',
            table='yeoman_core_calendarsynclog',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='yeoman_core_notification',
        ),
        migrations.AlterModelTable(
            name='notificationlog',
            table='yeoman_core_notificationlog',
        ),
        migrations.AlterModelTable(
            name='notificationpreference',
            table='yeoman_core_notificationpreference',
        ),
    ]
