# Generated by Django 6.0.3 on 2026-04-02 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keel_accounts', '0006_add_beta_tester_to_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(db_index=True, default='received', max_length=50)),
                ('submitter_first_name', models.CharField(max_length=128)),
                ('submitter_last_name', models.CharField(max_length=128)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitter_phone', models.CharField(blank=True, max_length=50)),
                ('submitter_organization', models.CharField(blank=True, max_length=255)),
                ('submitter_title', models.CharField(blank=True, max_length=255)),
                ('event_name', models.CharField(max_length=500)),
                ('event_description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('event_time_start', models.TimeField()),
                ('event_time_end', models.TimeField(blank=True, null=True)),
                ('event_timezone', models.CharField(default='America/New_York', max_length=50)),
                ('event_format', models.CharField(choices=[('presentation', 'Presentation'), ('keynote', 'Keynote'), ('panel_moderator', 'Panel Moderator'), ('panel_participant', 'Panel Participant'), ('site_visit', 'Site Visit'), ('roundtable', 'Roundtable'), ('ribbon_cutting', 'Ribbon Cutting'), ('meeting', 'Meeting'), ('reception', 'Reception'), ('conference', 'Conference'), ('fireside', 'Fireside Chat'), ('tour', 'Tour'), ('other', 'Other')], max_length=50)),
                ('event_format_other', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], max_length=20)),
                ('venue_name', models.CharField(blank=True, max_length=500)),
                ('venue_address', models.TextField(blank=True)),
                ('venue_city', models.CharField(blank=True, max_length=255)),
                ('venue_state', models.CharField(default='CT', max_length=2)),
                ('venue_zip', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('virtual_platform', models.CharField(blank=True, max_length=255)),
                ('virtual_link', models.URLField(blank=True)),
                ('delegated_at', models.DateTimeField(blank=True, null=True)),
                ('delegation_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('expected_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('surrogate_ok', models.BooleanField(default=True, help_text='Submitter is interested in a surrogate if principal has a conflict.')),
                ('press_expected', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('will_be_recorded', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10)),
                ('decline_reason', models.TextField(blank=True)),
                ('calendar_event_id', models.CharField(blank=True, help_text='External calendar event ID after push (Exchange/Google).', max_length=500)),
                ('calendar_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('status_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='keel_accounts.agency')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The staff member currently responsible for this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_invitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delegated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_made', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, help_text='If delegated, the person who will attend on behalf of the principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelegationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_log_by', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_log_to', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_history', to='yeoman.invitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='invitation_attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_by_staff', models.BooleanField(default=False, help_text='True if uploaded by internal staff, False if from submitter.')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='yeoman.invitation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvitationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_tags', to='keel_accounts.agency')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('agency', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='yeoman.invitationtag'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['agency', 'status'], name='yeoman_invi_agency__4f4c75_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event_date'], name='yeoman_invi_event_d_893da7_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['assigned_to', 'status'], name='yeoman_invi_assigne_bba43d_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['delegated_to'], name='yeoman_invi_delegat_f1abce_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['latitude', 'longitude'], name='yeoman_invi_latitud_f54197_idx'),
        ),
    ]
