# Generated by Django 6.0.3 on 2026-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='submitter_name',
        ),
        migrations.AddField(
            model_name='invitation',
            name='expected_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='press_expected',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='invitation',
            name='submitter_first_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='submitter_last_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='surrogate_ok',
            field=models.BooleanField(default=True, help_text='Submitter is interested in a surrogate if principal has a conflict.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='will_be_recorded',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Yes'), ('no', 'No')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event_format',
            field=models.CharField(choices=[('presentation', 'Presentation'), ('keynote', 'Keynote'), ('panel_moderator', 'Panel Moderator'), ('panel_participant', 'Panel Participant'), ('site_visit', 'Site Visit'), ('roundtable', 'Roundtable'), ('ribbon_cutting', 'Ribbon Cutting'), ('meeting', 'Meeting'), ('reception', 'Reception'), ('conference', 'Conference'), ('fireside', 'Fireside Chat'), ('tour', 'Tour'), ('other', 'Other')], max_length=50),
        ),
    ]
