# Generated by Django 6.0.3 on 2026-04-12 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keel_accounts', '0007_notificationpreference_channel_boswell'),
        ('yeoman', '0002_alter_invitationattachment_file_invitationnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text="e.g. Commissioner O'Keefe", max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal_profile', to='keel_accounts.agency')),
            ],
            options={
                'verbose_name': 'Principal Profile',
            },
        ),
        migrations.CreateModel(
            name='ReferenceAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. Home, Office, Capitol', max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='yeoman.principalprofile')),
            ],
            options={
                'verbose_name': 'Reference Address',
                'verbose_name_plural': 'Reference Addresses',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
