# Generated by Django 6.0.3 on 2026-04-15 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman', '0003_principalprofile_referenceaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='beacon_contact_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invitation',
            name='beacon_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='beacon_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='beacon_status',
            field=models.CharField(blank=True, choices=[('', 'Undecided'), ('added', 'Added to Beacon'), ('declined', 'Skipped')], default='', help_text='Whether this submitter has been pushed to Beacon.', max_length=10),
        ),
    ]
