# Generated by Django 6.0.3 on 2026-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman', '0004_invitation_beacon_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='modality',
            field=models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=20),
        ),
    ]
