# Generated by Django 6.0.3 on 2026-04-17 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeoman', '0006_invitation_calendar_sent_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='principal',
            field=models.ForeignKey(blank=True, help_text='The principal — person attending to speak at the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The claimant — staff member who manages logistics and confirmations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
